os:
- linux
language: python
python:
- 3.7
branches:
  except:
  - gh-pages
install:
- pip install tox
stages:
- name: lint
- name: test
- name: build
script: skip
jobs:
  fast_finish: true
  include:
  - stage: lint
    script: tox -e lint
    python: 3.7
    name: Lint
  - stage: test
    script: tox -e test
    python: 3.7
    name: Unit Tests
  - stage: build
    python: 3.7
    name: Build Package
    script: tox -e build
    deploy:
      - provider: pypi
        skip_existing: true
        user: djpugh
        password:
          secure: UGvX3r6EgxmGHH6eUbZwbQZxMlOKUIivqtEorVVItFU4JjuaOAJvp9OCeylvXWZOtVfOvAHgRb+SiDbrn07ksmLCwgZLNkwzc6oSZ8pwnOS6OE77LlYwlRK+GuWSdEt1Ourn/jVX5Kr3rK6Xo+SSitE7A2H8/UGAjgt67VnYhrm7YaFAyxDHgmnCyzEjkENIob+eA6DpSh/kvjAPYMCKrPnln60+ahKGqwnBQ4cqQ4UE6l50BkFtMT0y3EbhxVQzXsxqeg56PERgohFhKqVnRN0yaR+4SJ1vSEKmLk0FVKexNxFVtTmm5LnX5yT8LB02w4RTKEWrQ1uqtl1LtphcdbtTVH+EUepKLpN6UxS1++FoXDHnFuFASv3/Hx9DHbgDWj6kOZ0NL2icqQqUs/T+bfHLJ36l4NifznK+GYu6vHT5NDv2tXyVCGBBL9WYmkX050v/MBf6vRSkqOaKb6MfVO6wOY7KYMUrMmwo2XCPaClJkPq5ziWpEZ5OvIZ59s6aBDa/ai/X970oNpzDKKUfhIiaDStvVo51C02GYNkNt/W/37q5HA09jbbHScmnKeaJU4SOxV2u8M9pQ84Gt/FGnG9z3q2DPpNqIUk4p4k03dY/j1Lg1fKm2BvoRRRla+1DzzZzqxocf2HH7/J/SX9G4sNSlIIaFFe8uQm4gji3vHk=
        on:
          repo: djpugh/docserver-client
          tags: true
      - provider: releases
        api_key:
          secure: M+FOWcx8JxgEgH9QUJy1yrGCSpDi2rOCZHGw7iNHIpvy5wAQRLh3jp5wsEAFqJzoUlSLCeX/4L2Mzlfsaey8rbnoB/wui8tWuEQrksdssQjSxEZM4BkzGl+mD+nvKjNDY7iBo7WXhMZaItNZrX6Jl/UwTUmnEEgkCNr9ns0Uibfffo991RQy5hZeZqZZHayF/kt9hdZ+WEdxKLQiOZZRmUwi0hd7oPJYqynTY330e3gJS+gpIu1SvUD/bsNAcyXk2eRdZaRQDLd47XSN2RyQ1iABWRMhXeyXVdEVUZnaSjR9OFE0xk6GGiR1VQnQqQ8RmFUmx2DXHVuqx/IJoOicqsrz9A8+koP8CAWADhog0aHgoqVDACShXiWw9m09wPPTGI0CneSFS+fs8PN3zlYRjfWtV9Jp7gcft0sCH0EkqLJEqRyV4Qx6Km2TBHMluDN55EV4nlBEV2xvgi+wOF5T3a7zRpCSbuOzLIsJhJErEU+pnJYQtw2JfZaVvM86IFrGq8RhyDtqNIcyrRZoyxf0awxRtmvMt2WYnkh5RuUf73ps64WXHbmKsWtLqjZOuO0vRj5gtCOSsaDjOOCtcN/I5F56JNWF3UkcPsEGQL7ieZ5hegXPf2bkCeMkmQlcGSXYezN/+MNIKeAIwxpcec3eQuOUAGkt/V3LU4tvG9jaNoI=
        file: dist/*
        on:
          repo: djpugh/docserver-client
          tags: true
          condition: $TRAVIS_TAG =~ ^\d+\.\d+\.\d+
$bash