os:
- linux
language: python
python:
- 3.7
branches:
  except:
  - gh-pages
install:
- pip install tox
stages:
- name: lint
- name: test
- name: build
- name: publish
  if: tag =~ ^\d+\.\d+\.\d+$
script: skip
jobs:
  fast_finish: true
  include:
  - stage: lint
    script: tox -e lint
    python: 3.7
    name: Lint
  - stage: test
    script: tox -e test
    python: 3.7
    name: Unit Tests
  - stage: build
    python: 3.7
    name: Build Package
    script: tox -e build-package
  - stage: publish
    python: 3.7
    name: Publish Package
    deploy:
      provider: pypi
      user:
        secure: bUR4u93SA+avNZErmVPay7tFAeZJasBUhsz6vTJ+R5PZZ+z7F3+DC/EFLZhRiPELrk3gfjgcjWU4jf8Gbq/ODWLxxUgV0ZxxWx06FNkSYi+qk6Wee07zTpHrhGmIZEGW+Sl7XpWPqBJWC41exPg/2jD+qnDuu1Fb9WrcbyPF0BXSrhDQnKCShuvsZG/6RKOSxS7lZKXcpEelrZ+AibBmTHe2es3QDzZoZiywRMenrGcUh8vR0vohYRTdIkQo9zlhfwH7/QbtgtYC7QvufCFriX5+X0Z4/GoFfb+55hdv4BPkgsj4yhCA7b7DgBF8JzaALykmg6e4tUXLmxQuFqsOQnHty+NR9L0lEWVlmlewFUFpv+hyNN20KCx5f0TYR4nN+qRjiSysk8anlqyFx8Sliud4bbmUhy3npb7I+LScf5ruPBuJuVJA2csN8FbUm5hMrtrzqpuinz9BCV1T0iHxVUcSQHOBLUsbh6JPM2D1Y2kXTxsuRZ1caPaG/GxVIMF6A/rntgW+dZXzMNzBkznfKkaOX4HvkN0T7m5ISfhW1c6IpW7Nc1F8mfLp7TsmIWoyHUA84SX5NyjngQyjGuCFA5K3J6EOJFblPWvPbYSat3dp88B2bJUWy2eRdfXJ5eOi79DbQGGYNJMu/onGQk6gTevV7qjUi7uTXY28MQzfwlU=
      password:
        secure: UGvX3r6EgxmGHH6eUbZwbQZxMlOKUIivqtEorVVItFU4JjuaOAJvp9OCeylvXWZOtVfOvAHgRb+SiDbrn07ksmLCwgZLNkwzc6oSZ8pwnOS6OE77LlYwlRK+GuWSdEt1Ourn/jVX5Kr3rK6Xo+SSitE7A2H8/UGAjgt67VnYhrm7YaFAyxDHgmnCyzEjkENIob+eA6DpSh/kvjAPYMCKrPnln60+ahKGqwnBQ4cqQ4UE6l50BkFtMT0y3EbhxVQzXsxqeg56PERgohFhKqVnRN0yaR+4SJ1vSEKmLk0FVKexNxFVtTmm5LnX5yT8LB02w4RTKEWrQ1uqtl1LtphcdbtTVH+EUepKLpN6UxS1++FoXDHnFuFASv3/Hx9DHbgDWj6kOZ0NL2icqQqUs/T+bfHLJ36l4NifznK+GYu6vHT5NDv2tXyVCGBBL9WYmkX050v/MBf6vRSkqOaKb6MfVO6wOY7KYMUrMmwo2XCPaClJkPq5ziWpEZ5OvIZ59s6aBDa/ai/X970oNpzDKKUfhIiaDStvVo51C02GYNkNt/W/37q5HA09jbbHScmnKeaJU4SOxV2u8M9pQ84Gt/FGnG9z3q2DPpNqIUk4p4k03dY/j1Lg1fKm2BvoRRRla+1DzzZzqxocf2HH7/J/SX9G4sNSlIIaFFe8uQm4gji3vHk=
      on:
        repo: djpugh/docserver